name: Created Notification

on:
  issues:
    types: [opened]
  discussion:
    types: [created]

jobs:
  notify-on-issue-created:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Create Issue Post
        if: github.event_name == 'issues'
        uses: jiacai2050/telegraph-action@v1
        id: telegraph-issue
        with:
          token: ${{ secrets.TELEGRAPH_TOKEN }}
          telegram-token: ${{ secrets.TELEGRAM_TOKEN }}
          chat-id: "@zig_cc"
          author-name: "ZigCC Team"
          title: "${{ github.event.issue.title }}"
          author-url: "${{ github.event.issue.html_url }}"
          body: |
            > 文章链接：${{ github.event.issue.html_url }}

            ${{ github.event.issue.body }}

      - name: Create Discussion Post
        if: github.event_name == 'discussion'
        uses: jiacai2050/telegraph-action@v1
        id: telegraph-discussion
        with:
          token: ${{ secrets.TELEGRAPH_TOKEN }}
          telegram-token: ${{ secrets.TELEGRAM_TOKEN }}
          chat-id: "@zig_cc"
          author-name: "ZigCC Team"
          title: "${{ github.event.discussion.title }}"
          author-url: "${{ github.event.discussion.html_url }}"
          body: |
            > 文章链接：${{ github.event.discussion.html_url }}

            ${{ github.event.discussion.body }}

      - name: Install pandoc
        if: github.event_name == 'issues'
        uses: pandoc/actions/setup@v1
      - name: Prepare Email Body
        if: github.event_name == 'issues'
        run: |
          pandoc -f markdown -t html -o email_body.html <<EOF
          > 原文链接：${{ github.event.issue.html_url }}

          ${{ github.event.issue.body }}
          EOF
      - name: Send Email
        if: github.event_name == 'issues'
        uses: jiacai2050/sendmail-action@v1
        with:
          smtp_url: 'smtps://smtp.gmail.com:465'
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          from: 'ZigCC Team <jiacai2050@gmail.com>'
          to: "zigcc@googlegroups.com"
          subject: "${{ github.event.issue.title }}"
          html_body_file: email_body.html

      # - name: Send Telegram Message
      #   uses: jiacai2050/telegram-action@v1
      #   with:
      #     message: "${{ steps.telegraph-issue.outputs.url || steps.telegraph-discussion.outputs.url }}"
